### ISSUE TITLE
How do Clarius's imu.yml files correspond to ST manufacturer data and application sheets? 

### ISSUE THREAD

**Issue by km414** [clariusdev/motion#14]
The attached sheets were pulled directly from ST's webpage:

"ClariusHD3_GyroscopeAccelerometer_ST lsm6ds0.pd" is the datasheet for the 3D accelerometer and 3D gyroscope in the Clarius HD3 ultrasound probes. 
[ClariusHD3_GyroscopeAccelerometer_ST lsm6ds0.pdf](https://github.com/clariusdev/motion/files/12134777/ClariusHD3_GyroscopeAccelerometer_ST.lsm6ds0.pdf)

"ClariusHD3_Magnetometer_ST lis2mdl.pdf" is the datasheet for the 3-axis magnetometer in the HD3 probes.
[ClariusHD3_Magnetometer_ST lis2mdl.pdf](https://github.com/clariusdev/motion/files/12134776/ClariusHD3_Magnetometer_ST.lis2mdl.pdf)

"dt0058-computing-tilt-measurement-and-tiltcompensated-ecompass-stmicroelectronics.pdf" is a design tip sheet associated with the LIS2MDL and the LSM6DS0.
[dt0058-computing-tilt-measurement-and-tiltcompensated-ecompass-stmicroelectronics.pdf](https://github.com/clariusdev/motion/files/12134775/dt0058-computing-tilt-measurement-and-tiltcompensated-ecompass-stmicroelectronics.pdf)

1. Are the raw measurements representative of what is described in the ST0058 Design Tip and Datasheet documentation?
2. Does Clarius's imu.yml data represent the tilt computation description in the ST0058 Design Tip documentation? If not, can you provide a corresponding document to clarify the imu calculations that Clarius is using? 
3. On Clariu's IMU page, https://github.com/clariusdev/motion, there is a statement with an image of the probe with axes: "The IMU sensor data is aligned to the axes as shown below. This is consistent across all Clarius probe generations." How do these axes correspond to the Earth's magnetic field? Does this image/axes correspond to those shown in ST's documentation?

**Comment by clariusk** [comment]
1. No we have not referenced the design tip document
2. For, roll, pitch, yaw, we take the quaternion data and compute the euler angles
3. yes they do
