### ISSUE TITLE
IMU in Slicer 3D view rearranging image

### ISSUE THREAD

**Issue by stka85** [clariusdev/motion#16]
Hello, I have connected the Clarius C3 HD3 to Slicer via the Plus Toolkit. According to the video https://www.youtube.com/watch?v=2vXeJxYFou4&t=4s, I expected the live image in the 3D view to rearrange itself while moving the scanner. I have also activated the IMU data transfer. Is there another setting that I am not aware of? Should this work? 
Is there any documentation on how to adjust the config file?
Thank you!
[PlusDeviceSet_Server_ClariusVideoCapture_IMU_Tracking.txt](https://github.com/clariusdev/motion/files/13704778/PlusDeviceSet_Server_ClariusVideoCapture_IMU_Tracking.txt)

**Comment by julien-l** [comment]
For integration issues, you should contact the support of Slicer or the Plus Toolkit, thanks.
