### ISSUE TITLE
Innacurate IMU captor

### ISSUE THREAD

**Issue by eclarius** [clariusdev/motion#2]
Hello,

We are testing the IMU sensor of the probe. After calibrating the probe with the app, we did a rotation of exactly 90 degree and back twice on our workbench and recorded the rotational speed. We simply integrated this speed to obtain the orientation:

<img width="300" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/102674190/160847859-38950b54-d40a-4e8e-80cc-05ff877c2d3a.png">

Unfortunately we obtain 75 degrees of rotation, which is a >15% error. Such error on an easy and short task makes the IMU data worthless on longer capture. To verify that this is not due to our code, we attached an iPhone on our workbench to capture simultaneously the same data (up to axis and directions):

<img width="300" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/102674190/160847824-ca93806b-d7bc-4cac-acc3-0afa68c52be5.png">

The integrated rotation gives us indeed 90 degrees:
<img width="300" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/102674190/160847846-4eb03877-0abd-46d0-83c4-ff77f6f0320a.png">

- Is there anyone using IMU data from the probe successfully?
- Is there a better way to calibrate the sensor?
- Is our probe defect?

Thank you for your help

**Comment by eclarius** [comment]
We are using the raw gyroscope data.

**Comment by clariusk** [comment]
ok great, the calibration will not have an effect then. once calibrated you can then use the quaternion data (if that helps with your positioning calculations) - you can see an example of how that data is used: https://github.com/clariusdev/motion/blob/master/pyimu/pyimu.py

**Comment by eclarius** [comment]
Great! That's much better :)

To understand better: the quaternions are computed from the gyroscope, accelerometer and magnetometer on the chip after calibration? Does that mean we should discard gyroscope and magnetometer data? Is the accelerometer calibrated and does it make sense to use it to find the (relative) position by double integration?

![output](https://user-images.githubusercontent.com/102674190/161237352-f0cdc6bc-9379-4ba0-9d27-5d4d0ec2cc63.png)

**Comment by clariusk** [comment]
- yes, the quaternion data is calculated from the raw data with calibration data applied.
- not sure if you need to discard everything, for our basic rotation algorithms, we just use the calibrated data, but if you're looking to do translation, perhaps there's more methods that need to be applied on the raw data (sorry the spatial transformations are not my background)
