### ISSUE TITLE
IMU captor position

### ISSUE THREAD

**Issue by eclarius** [clariusdev/motion#3]
Please provide the distance from scanning plane to internal sensor for the new scanner model (C3HD). This is needed to apply rotation quaternion to the CAD model. Finding this position ourselves is too difficult given inaccuracies in #2 .

**Comment by clariusk** [comment]
is this for HD or HD3 model, if HD, then the internal CAD is provided here: https://github.com/clariusdev/cad/blob/main/hd.zip

**Comment by eclarius** [comment]
Thanks for your answer.

We have the HD. I checked the CAD file and it does not contain any electronical component. There is also an `imu.step` file but I don't think it's for the C3HD.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/102674190/160992798-e70caa73-e314-43a9-aa2f-244937ba32ad.png">

Let us know where is the IMU sensor in our probe.

**Comment by clariusk** [comment]
you can actually use the imu.step file, ignore the model of the scanhead, all of our devices have the same inside

**Comment by eclarius** [comment]
Is it at the center of the red rectangle?

<img width="942" alt="image" src="https://user-images.githubusercontent.com/102674190/161211549-767c4b10-2fd2-4392-93b1-ff8b9db25e72.png">

It would be much more reliable for every users if you indicated the position of the captor for all the HD and HD3 probes as you did for your v1.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/102674190/161211688-fd2433fe-0da0-4746-ada4-fe37bd53ac56.png">

**Comment by clariusk** [comment]
check out the opposite side, the small solid rectangle.
![imu-pos](https://user-images.githubusercontent.com/8701648/161597248-d5a7afaf-ba24-4eb9-aca7-c63aa571d271.png)

**Comment by eclarius** [comment]
Thanks for your reply. According to our measurement the captor is at -116mm from the imaging plane on the z-axis and we will assume it is centered on the x- and y-axis.
